### ISSUE TITLE
Unsure how to clear history of Psensor 

### ISSUE THREAD

**Issue by pallebone** [chinf/psensor#3]
Hi there,

If I reboot the system I can clear the values and history of psensor (like max/min temperatures reached), but this is not always convenient and I am not able to determine how to do this without rebooting the system. is there a file that I need to delete that would clear the psensor data and make it start again so that I can avoid rebooting after an external event (eg: air conditioner maintenance) that allows me to get more accurate reading of max and min values once that external event has passed?

Thanks in advance 
Pete

**Comment by iz-floresta** [comment]
Was just trying to figure this out. My solution is to issue is to kill the Psensor from the terminal:

```killall psensor

If you're looking for the logs they're at 

```/home/<user>/.psensor

I renamed the file 'log' to 'log.old'
A new 'log' file when the program was restarted, but it did not clear values in the GUI, which I believe is the effect we're going for.
Hope this helps.

**Comment by iz-floresta** [comment]
Was just trying to figure this out. 

If you're looking for the logs they're at: 

    /home/<user>/.psensor

Tried closing the program and renamed the file 'log' to 'log.old'.
When the program was restarted, a new 'log' file was generated in the same location,  but it did not clear values in the GUI, which I believe is the effect we're going for.

My solution is to issue is to kill the Psensor from the terminal:

    killall psensor

No restart needed. Hope this helps.

**Comment by pallebone** [comment]
Thanks thats perfect.
